name: Publish release on push

on:
  push:
    branches:
      - master

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup build cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

        run: |
          # Generate a new version based on the timestamp or commit hash
          NEW_VERSION=$(date +%Y%m%d%H%M%S)  # Or use another strategy
          echo "New version: ${NEW_VERSION}"

          # Print the GitHub username of the actor triggering the workflow
          echo "GitHub username: ${GITHUB_ACTOR}"

          # Run the Gradle task to publish the artifact
          ./gradlew -Pversion=${NEW_VERSION} publish

