name: Auto Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Git Credential Cache
        run: git credential-cache exit

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set executable permissions
        run: chmod +x ./gradlew
        working-directory: ./paper

      - name: Extract Version from gradle.properties
        id: extract_version
        run: echo "::set-output name=version::$(grep -Po '(?<=version=).+' ./paper/gradle.properties)"

      - name: Build and Publish
        run: ./gradlew clean build publishToMavenLocal
        working-directory: ./paper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: |
            Automatic release generated by GitHub Actions.
            Build artifact: ${{ steps.build.outputs.artifact }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release Artifact
          path: ./paper/build/libs/
